### ISSUE TITLE
Пересчет lft, rgt

### ISSUE THREAD

**Issue by qantus** [studio107/Mindy_Orm#50]
`$modelClass::objects()->filter(['pk__in' => $data])->delete();`
В ModelAdmin - нужно чтобы при удалении Nested моделей пересчитывались lft, rgt

**Comment by max107** [comment]
После удаления выполнить дополнительный запрос на пересчет "пробельных" мест в дереве

**Comment by tsukasa-mixer** [comment]
получается надо выполнить что-то типо такого запроса

update 	{{tablename}} t, {{tablename}} tt
set 	t.lft = IF(t.lft < :deleted_lft, tt.lft, tt.lft-2), 
		t.rgt = tt.rgt-2
where	(t.lft > :deleted_lft or t.rgt > :deleted_rgt) 
	and t.root = :deleted_root 
	and t.id = tt.id

**Comment by max107** [comment]
@tsukasa-mixer "что то типо" или ты все же проверил запрос в деле?

**Comment by tsukasa-mixer** [comment]
на тестовых данных, да.
Но еще погоняю пару тестов для уверенности.

**Comment by max107** [comment]
Ок, жду.

**Comment by tsukasa-mixer** [comment]
т.к. задача сваять кросплатформенно для разных БД, то все-же придется разложить на отдельные запросы и максимально их упростить.

получаем все проблемные элементы дерева
```sql
select id, root, lft, rgt from {{table_name}} t
where not t.lft = (t.rgt-1)
and not id in (	select tc.parent_id from {{table_name}} tc where tc.parent_id = t.id );
```

Для каждого полученного проблемного элемента выполняем традиционные

```sql
update {{table_name}} tu,  {{table_name}} ts
set tu.lft = ts.lft-2, tu.rgt = ts.rgt-2
where ts.id = tu.id
  and tu.root = :bad_root
  and tu.lft >  :bad_rgt; 

update {{table_name}} tu,  {{table_name}} ts
set tu.rgt = ts.rgt-2
where ts.id = tu.id
  and tu.root = :bad_root
  and tu.lft <  :bad_rgt
  and tu.rgt >= :bad_rgt;
```
update выполнять за 1 транзакцию.

данный код не содержит платформозависимых элементов и должен быть универсальным, из минусов, большое количество запросов.

если писать платформозависимо - можно значительно сократить количество запросов.

**Comment by qantus** [comment]
Суть в том, что мне нужно удалить пачку элементов, пересчитав корректно дерево, а там я мог удалить: корень дерева без дочерних элементов, всех дочек у отдельного объекта, часть предыдущих элементов, часть последующих элемнтов и так далее.

**Comment by max107** [comment]
@qantus не, суть данной задачи именно в удалении объектов по `filter()->delete()` и последующий эвент который исправит или выявит проблемные участки

**Comment by tsukasa-mixer** [comment]
@qantus то, что ты хочешь - это уже на полноценный анализ дерева и полную перестройку тянет, а это средствами одного тока sql сделать тяжело (точнее мультиплатформенно это не сделать и придется писать под каждую базу свою процедуру которая будет делать это, особенно в ключе если грохнул корень но не грохнулись дочки это:
 - запрос количество различающихся корней
 - перестройка для каждого корня всех значений lft-rgt по id-parent_id игнорируя level )

т.е. разумно после удаления элемента дерева делать 2 апдейта которые будут шевелить дерево.
