### ISSUE TITLE
Ошибки GD

### ISSUE THREAD

**Issue by qantus** [studio107/Mindy_Orm#72]
Существуют некоторые файлы *.jpeg, которые открываются методом imagecreatefromjpeg(), но не открываются методом imagecreatefromstring() и ImageField просто игнорирует данные файлы

**Comment by max107** [comment]
@qantus вынеси ишью в Mindy плз

**Comment by qantus** [comment]
Ошибка обнаружена - сторонний сервер произвольным образом сжимает изображения. Заголовок: application/x-gzip. Решено добавить проверку на данный тип и пробовать его "распаковать" для чтения.

**Comment by qantus** [comment]
Проблема была локальной и принято решение сделать RemoteGzipFile под проект. Если кому нужно - поделюсь, но особого смысла хранить это в Mindy_Storage.

**Comment by max107** [comment]
Как на счет вынести эту проверку в `RemoteFile` как ты ранее говорил?
