### ISSUE TITLE
Корректность ORDER с JOIN

### ISSUE THREAD

**Issue by max107** [studio107/Mindy_Orm#73]
Таблица `tests_users`:
```
id int
username string
password string
```

Данные:
```
1 foo qwe
2 bar qwe
```

Таблица `tests_customer`
```
id int
user_id int
address text
```

Данные:
```
1 1 home
2 2 home
3 2 work
```

Запрос:
```php
User::objects()->order(['-addresses__address'])->all()
```

где `addresses` это связь `has_many` до `tests_customers`

Ожидаемый результат с учетом `JOIN` и `ORDER`: 3 записи. На текущий момент реализован `DISTINCT` + `GROUP` (работает в sqlite, mysql) и не корректно работат в pgsql, но возвращает 2 результата.

Какой результат выборки все же должен быть правильным / очевидным?

**Comment by max107** [comment]
@tsukasa-mixer @qantus @AlexandrGordeev

**Comment by max107** [comment]
@qantus дело пахнет керосином, так как твоя логика с `DISTINCT` является не корректной со следующей точки зрения:

Субд возвращает 3 записи, следовательно должно быть 3 модели, не смотря на то, что они дублирующие. Логика не очевидна на более сложных запросах, так как `DISTINCT` может быть по другому полю. А в данном конкретном случае он не указан.

**Comment by tsukasa-mixer** [comment]
Итак исходя из предварительного диалога в ВК мое мнение и предполагаемого запроса.

SELECT tests_user.*
FROM tests_user
LEFT JOIN tests_customer ON tests_user.id = tests_customer.user_id
GROUP BY tests_user.id, tests_customer.address
ORDER BY tests_customer.address DESC;

Корректным результатом будет 3 записи т.к. запрос прдполагает выборку уникальных наборов записей.
Набор по полям п=группировки будет таким:
user.id, customer.address
1 home
2 home
2 work

Также смею отметить что MySql и производные, одна из немногих баз данных в которых выборка может отличатся от сортировки и группировки, во многих других, если ты сортируешь или группируешь по полям - то долже добавить их в список выбираемых.

уникальных пользователей с сортировкой по адресу (что само по себе является достаточно странным действием) достаточно исподльзовать distinct.

а вообще как уже писал, 3 записи без дистинктов это корректный результат.

**Comment by max107** [comment]
Так же в случае с `pgsql` поле с `DISTINCT` будет участвовать в `SELECT`. В случае использования `asArray`, к примеру, в `RESTful` - будут лишние данные. Убрать лишние данные можно лишь пост обработкой результатов выборки, что накладывает определенные ограничения.

Пример: asArray() используется практически со скоростью `PDO` и накладные ресурсы на пост обработку даже 10 000 объектов будут сильно заметны.

**Comment by AlexandrGordeev** [comment]
По документации результат должен быть 3 записи. Это более чем очевидно, но не совсем удобно. Вывод, запрос должен вернуть 3 записи, не добавляя лишнее к запросу, таким образом перекладывая на разработчика всю ответственность за использование методов для построения запроса.

**Comment by max107** [comment]
Результат: выносить `DISTINCT` в отдельный метод ORM с указанием полей по которым собственно происходит `DISTINCT`.

Синтаксис:
```php
$qs->distinct(['id']); // по 1 полю
```

```
$qs->distinct(); // по всем полям
```

```
$qs->distinct(['id' => 'id']); // по 1 полю с ON. Характерно для pgsql
```

В случае если конкретная субд не поддерживает `DISTINCT` в полной мере (в сравнении с pgsql) то вызывать Exception.

**Comment by tsukasa-mixer** [comment]
можно и так.
если проверяется тип соединения то можно проверить возможности  СУБД по функциональности и если этой возможности нет, то генерить эксепшен.

из проблем:
 - При переезде между разными БД придется писать разный код или корректировать запросы.
- вопрос производительности фичь.

**Comment by max107** [comment]
Django:

> Any fields used in an order_by() call are included in the SQL SELECT columns. This can sometimes lead to unexpected results when used in conjunction with distinct(). If you order by fields from a related model, those fields will be added to the selected columns and they may make otherwise duplicate rows appear to be distinct. Since the extra columns don’t appear in the returned results (they are only there to support ordering), it sometimes looks like non-distinct results are being returned.

[distinct](https://docs.djangoproject.com/en/dev/ref/models/querysets/#distinct)

**Comment by tsukasa-mixer** [comment]
PGSQL - distinct в данном случае достаточно уникален и я бы отнес его к разряду фичь
MSSql, Oracle, MySQL - distinct работает идентично. возможны вариации от набора фичь конкретной СУБД.

**Comment by max107** [comment]
И все же, @AlexandrGordeev был прав. С точки зрения ORM мы должны получить 2 записи, если явно не указано иначе.

Очевидное лучше чем не очевидное.

```php
// Ожидаем выбирать только уникальных (без дубликатов) пользователей
User::objects()->filter(['cutomer__address__startswith' => 's'])->order(['groups__name' => 'Developer']);
```

Предлагаемый синтаксис:

```php
// Получаем сырые записи (как есть из SQL)
User::objects()->filter(['cutomer__address__startswith' => 's'])->order(['groups__name' => 'Developer'])->distinct(false)->group(false);
```

**Comment by max107** [comment]
В Django выбираются 3 записи (объекта), но на выходе мы видим 2 модели. Запрос формируемый Django:

```sql
"SELECT "main_person"."id", "main_person"."name" 
FROM "main_person" 
LEFT OUTER JOIN "main_customer" ON ( "main_person"."id" = "main_customer"."user_id" ) 
ORDER BY "main_customer"."address" DESC"
```

Postgresql при таком запросе возвращает 3 записи, что логично. Где то в недрах Django, что то происходит, как то работает и возвращается в итоге 2 модели. Проблематично найти именно тот кусок кода, где происходит обработка.

**Comment by max107** [comment]
## Решение №1

```sql
SELECT *
FROM (
	SELECT DISTINCT ON ("tests_user_1"."id") "tests_user_1"."id",  "tests_user_1".*, "tests_customer_2"."address"
	FROM "tests_user" "tests_user_1"
	LEFT OUTER JOIN "tests_customer" "tests_customer_2" ON "tests_user_1"."id" = "tests_customer_2"."user_id"
	GROUP BY "tests_customer_2"."address", "tests_user_1"."id", "tests_user_1"."username", "tests_user_1"."password"
	ORDER BY "tests_user_1"."id", "tests_customer_2"."address" DESC) "_tmp"
ORDER BY "_tmp"."address"
```

**Comment by max107** [comment]
![screen shot 2015-02-09 at 20 32 40](https://cloud.githubusercontent.com/assets/862272/6111707/fab55680-b09b-11e4-80d7-d6d993b31916.png)
