### ISSUE TITLE
Метод order

### ISSUE THREAD

**Issue by AlexandrGordeev** [studio107/Mindy_Orm#86]
В методе отсутствует возможность использовать функции без указания колонки для сортировки, что приводит к неправильному запросу.
OrmModel::objects()->order(['RAND ()'])->all();

**Comment by qantus** [comment]
OrmModel::objects()->order(['?])->all();

**Comment by AlexandrGordeev** [comment]
Закрыто, добавить в readme

**Comment by qantus** [comment]
Добавлено в Readme
